@echo off
echo Initializing git...
git init
echo Adding files...
git add .
echo Committing files...
git commit -m "Initial commit: Complete Full-Stack Salon Appointment Booking System"
echo Setting branch...
git branch -M main
echo Adding remote...
git remote add origin https://github.com/kushmahatara/salon-appointment-booking.git
echo Pushing to GitHub...
git push -u origin main
echo Done.
pause
